# -*- coding: utf-8 -*-
"""2 실습 Pandas-2.ipynb의 사본의 사본

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12kOtgMKQ36TpJta-EGiUSrtCnmN6kW2U

winemag-data.csv 파일을 reviews 로 읽는다.
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

import os

os.chdir('/content/drive/MyDrive/ai교육/ML-01-main/day01')

df = pd.read_csv('winemag-data.csv', index_col = 0)

"""인덱스를 title 컬럼으로 셋팅한다."""

df.head()

df.index = df['title']

df.head()

"""먼저 데이터가 비어있느것이 있는지 확인한다."""

df.isna().sum()



"""그리고나서, 가격이 없는 데이터는 빼고, 데이터셋을 가져온다."""

df['price'].notna()

df.loc[df['price'].notna(),]

"""리뷰에 새로운 컬럼 critic 만들고, everyone 이라고 값 넣는다."""

df.head()

df['critic'] = 'everyone'

df.head()

"""리뷰의 포인트 컬럼은 수치로 되어있다. 이 컬럼의 기초통계데이터를 확인하시오. (평균, 최대 최소 등)"""

df['points'].mean()

df['points'].min()

max_point = df['points'].max()

df['points'].describe()

"""점수를 100점 맞은 와인의 데이터를 가져오시오.  """

df_100 = df.loc[df['points']== 100, ]

df_100.shape

df_100.sort_values('price')

"""taster_name 컬럼은 사람 이름으로 되어있다. 몇명의 사람들이 평가를 한것인까?"""

df.head()

df['taster_name'].shape

df['taster_name'].nunique

df['taster_name'].describe

"""리뷰 포인트의 평균을 구하시오"""

df['points'].mean()





"""테스터들의 이름을 전부 확인하시오"""

df['taster_name'].unique()



"""각 테스터들은, 각각 몇개의 와인을 테스트 했는지 확인하시오. ( 테스터 이름, 갯수 )"""

df['taster_name'].value_counts()

"""리뷰의 포인트의 평균을 구하고, 리뷰의 포인트값이, 평균보다 큰 데이터 (즉, 평가가 좋은 와인) 만 가져오시오."""

df_mean = df['points'].mean()

df.loc[df['points']>df_mean,]



