# -*- coding: utf-8 -*-
"""3 실습 Pandas-3.ipynb의 사본의 사본

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SbSuK3PSud75cAJXaK5mBPz-1ab5MOa8

winemag-data.csv 파일을 reviews 로 읽는다.
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

import os

os.chdir('/content/drive/MyDrive/2021 ai 교육/ML-01-main/day01')

df = pd.read_csv('winemag-data.csv', index_col = 0)

"""리뷰 데이터프레임에서 points 컬럼의  median 값은?"""

df['points'].median()



"""나라를 중복되지 않도록 가져와서 countries 변수에 저장하고, 화면에 출력하시오."""

df['country'].nunique()

country = df['country'].nunique()

df['country'].describe()

"""각 국가별로는 몇개의 리뷰가 있는지, 각국가별 리뷰수를 구하시오."""

df['country'].value_counts()

df['country'].unique()
# unique - 고유값들 출력
# nunique - 고유값의 개수를 출력



"""리뷰 데이터프레임의 price 컬럼 값에서, price의 평균값을 뺀 값을, centered_price 라고 저장하시오."""

centered_price = df['price'] - df['price'].mean()

df['centered_price'] = centered_price

df.head()



"""나는 경제적이므로, 가격대비 포인트가 가장 큰 와인을 사려한다. 해당 와인의 title은?"""

df['new'] = df['points'] / df['price']

df.sort_values('new',ascending = False)

"""사람들이 어떤와인을 더 많이 거론했는지 보려한다.

"tropical" 이 들어있는 리뷰의 갯수를 세고, "fruity" 라고 들어있는 리뷰의 갯수를 세어서

판다스 시리즈로 descriptor_counts 변수로 만들어 보자.
"""

df['description'].str.contains('tropical')
# description columns에서 tropical이란 단어가 들어간 리뷰 찾는 과정

df['description'].str.contains('fruity')

df_tropical = df.loc[df['description'].str.contains('tropical'),]

df_tropical.shape

df_fruity = df.loc[df['description'].str.contains('fruity')]

df_fruity.shape



"""별점 시스템을 만들려고 한다. 따라서 별점에 대한 데이터가 필요하다.

별점은 1,2,3 즉 3개로 만들것이다.

포인트가 95점 이상이면 3점, 85점 이상이면 2점, 나머지는 1점으로 할 것이다. 

리뷰데이터를 통해 각 데이터의 별점을 구하시오.
"""

def get_star(point):
  if point >= 95:
    return 3
  elif point >= 85:
    return 2
  else :
    return 1

df['star'] = df['points'].apply(get_star)

df.head()







"""리뷰의 region_2 컬럼에 데이터가 비어있는 경우에는, 'Unknown'으로 셋팅하자."""

df['region_2'].fillna('Unknown')



"""포인트로 그룹바이하고, 몇개의 데이터가 있는지 카운팅"""

df.head(2)

df.groupby('points')['points'].count()



"""포인트별 가격의 최소값을 구해본다."""

df.groupby('points')['price'].min()

"""각 국가별로, 가격의 최소값, 최대값 은?"""

min1 = df.groupby('country')['price'].min()
max1 = df.groupby('country')['price'].max()
print(min1,max1)

# numpy로 하는 법
import numpy as np

df.groupby('country')['price'].agg([np.min,np.max])